### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by brad0taylor** [conda-forge/caffe-feedstock#31]
Thanks you for providing this awesome recipe.  I'm having some issues with using the install and perhaps this is a good place to ask. (if not apologies)  I've installed caffe as follows:

- conda create -n caffe
- conda install python=3.5
- conda install -c conda-forge caffe 
- conda install caffe
- When I open python and run ">>>import caffe * " I get the following error. 

ImportError: libprotobuf.so.12: cannot open shared object file: No such file or directory

I see  /home/brad/anaconda3/envs/caffe/lib/libprotobuf.so.13 but not  .so.12. Unfortunately I dont know to get the .12 version. Can you suggest a fix?

Thanks

**Comment by dougalsutherland** [comment]
I just got the same error; I suppose that protobuf needs to be pinned (https://github.com/conda-forge/conda-forge.github.io/pull/411).

**Comment by dougalsutherland** [comment]
Actually, it seems that this recipe is only built for python 2.7 for some reason, so @brad0taylor you're probably using the version of caffe from the default repositories. Same fix applies.

**Comment by shamangary** [comment]
After I have the similar error on python3.5, I reinstall a environment for python2.7. But the error still remain.

```
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shamangary/anaconda2/envs/py2cv3/lib/python2.7/site-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/shamangary/anaconda2/envs/py2cv3/lib/python2.7/site-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libprotobuf.so.10: cannot open shared object file: No such file or directory
>>> 
```
And I do
```
conda install protobuf=3.2
```
But the error is still there. Plz help?

**Comment by dougalsutherland** [comment]
@shamangary, I think this should be fixed if you `conda install caffe=1.0` (in about 10 minutes, when https://circleci.com/gh/conda-forge/caffe-feedstock/78 finishes).

**Comment by salvador-blanco** [comment]
I'm trying to to be able to run this demo https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation

I'm running ubuntu 14.04

I have installed Anaconda, and after installing many many many dependencies another one pops. It also requires python caffe

So I installed it with this command:
(I also tried `Pip install caffe` but if failed)
$ `Conda install caffe`
But then when I try to run it I get:

    ```
$ python
    >>> import caffe
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/gtkratosman-lap/anaconda2/lib/python2.7/site-packages/caffe/__init__.py", line 1, in <module>
        from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
      File "/home/gtkratosman-lap/anaconda2/lib/python2.7/site-packages/caffe/pycaffe.py", line 13, in <module>
        from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
    ImportError: libprotobuf.so.12: cannot open shared object file: No such file or directory)
```

**Comment by dougalsutherland** [comment]
@salvador-blanco, make sure you're using the conda-forge version and don't have any partial pip-installed dependencies floating around. Easiest way is to make a new environment to test:
```
conda create -n caffetmp -c conda-forge caffe
source activate caffetmp
python -c 'import caffe'
```
If that works, it means something is messed up in your other environment, probably from mixing incompatible versions of packages from various sources.

**Comment by salvador-blanco** [comment]
`conda install caffe=1.0`
Did not work for me I still get the same error

**Comment by jakirkham** [comment]
Please share your full environment. Also please make sure you have `protobuf` 3.4 not 3.5.

**Comment by salvador-blanco** [comment]
So after doing 
```
conda create -n caffetmp -c conda-forge caffe
source activate caffetmp
python -c 'import caffe'
```
I was able to use caffe on the caffetmp virtual environment, which means my other environments are messed up.
If I want to install caffe outside the environment how should I do it? 
I have cleaned everything, so I can have a fresh start

**Comment by salvador-blanco** [comment]
I tried installing 
`conda install caffe`
but I get the following error:
```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::opencv-3.1.0-np112py27_1'.
OSError(13, 'Permission denied')
```

**Comment by jakirkham** [comment]
Sounds like some sort of `conda` problem. Could you please raise upstream? Also please make sure to give them enough info to work with. Thanks.

**Comment by jakirkham** [comment]
Closing as it appears the original issue has been resolved.

**Comment by nanodust** [comment]
no luck w/ caffe-gpu, same libprotobuf.so.12 error.

**Comment by jakirkham** [comment]
That's an unrelated issue, @nanodust.

**Comment by hossam-96** [comment]
> @salvador-blanco, make sure you're using the conda-forge version and don't have any partial pip-installed dependencies floating around. Easiest way is to make a new environment to test:
> 
>  ```
>  conda create -n caffetmp -c conda-forge caffe
>  source activate caffetmp
>  python -c 'import caffe'
>  ```
> 
> If that works, it means something is messed up in your other environment, probably from mixing incompatible versions of packages from various sources.

and how can i fix this if there is something messed up in my environment without making new one?

**Comment by StYumXmas** [comment]
Looks like I have found the solution.
Check your libprotobuf version:
`conda list libprotobuf`
if it's 3.4.0, you should downgrade it to 3.2.0
`conda install libprotobuf=3.2.0`
then try it again and it should be ok. 
@brad0taylor

**Comment by IngleJaya95** [comment]
from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libprotobuf.so.10: cannot open shared object file: No such file or directory

Failing with conda install libprotobuf=3.2.0
conda install caffe=1.0

**Comment by getamu** [comment]
> conda install caffe=1.0

I am getting `Packages NotFoundError: The following packages are not available from current channels:`

**Comment by advance512** [comment]
If you're installing caffe via conda and running into this, try:
```
conda install python=2.7 caffe-gpu protobuf gflags
```
